#!/bin/sh

function changed {
    git diff --name-only HEAD@{1} HEAD | grep "^$1" >/dev/null 2>&1
}

echo 'Checking for changes in pnpm-lock.yaml...'

if changed 'pnpm-lock.yaml'; then
    echo "pnpm-lock.yaml changed. Running pnpm install to update dependencies..."
    pnpm install
fi

echo '✨ You are up to date!'

exit 0