name: Expo Doctor (expo)

on:
  push:
    branches:
      - main
      - master
    paths:
      - 'package.json'
      - 'bun.lockb'
  pull_request:
    paths:
      - 'package.json'
      - 'bun.lockb'

jobs:
  doctor:
    name: Expo Doctor (expo)
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write

    steps:
      - name: 📦 Checkout project repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: 📦 Setup Node + PNPM + install deps
        uses: ./.github/actions/setup-node-pnpm-install

      - name: Run prebuild
        run: bun prebuild:clean

      - name: 🚑 Run Doctor Checks
        run: |
          chmod +x .github/scripts/expo-doctor.sh
          rm -rf ios android
          .github/scripts/expo-doctor.sh

      - name: Add doctor report as comment on PR
        if: github.event_name == 'pull_request' && always()
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          header: expo-doctor
          path: .expo/expo-doctor.md
